import Database from "better-sqlite3";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createFreshStore } from "../../src/storage/bootstrap.js";
import { createBoard } from "../../src/domain/boards.js";
import { defineTask } from "../../src/domain/tasks.js";
import { claimAttempt } from "../../src/domain/attempts.js";
import { transitionTask, TaskTransitionError } from "../../src/domain/task-transitions.js";
let db: Database.Database;
afterEach(() => db?.close());
function open() { db = new Database(":memory:"); createFreshStore(db); createBoard(db, { id: "b", project: "p", name: "b", actor: "a", idempotencyKey: "b" }); defineTask(db, { id: "t", boardId: "b", title: "t", priority: "p1", actor: "a", idempotencyKey: "t", expectedBoardRevision: 1 }); return db; }
it("transitions with attempt authority, CAS, and idempotent replay", () => { const d = open(); const c = claimAttempt(d, { boardId: "b", taskId: "t", actor: "a", expectedTaskRevision: 1, leaseSeconds: 15, idempotencyKey: "c" }); const i = { boardId: "b", taskId: "t", actor: "a", attemptId: c.attemptId, claimToken: c.claimToken!, expectedRevision: 2, target: "in_review" as const, idempotencyKey: "x" }; expect(transitionTask(d, i)).toMatchObject({ status: "in_review", taskRevision: 3 }); expect(transitionTask(d, i)).toMatchObject({ status: "in_review" }); expect(() => transitionTask(d, { ...i, idempotencyKey: "bad", claimToken: "wrong" })).toThrow(TaskTransitionError); });
it("closes failed attempts and rejects terminal tasks", () => { const d = open(); const c = claimAttempt(d, { boardId: "b", taskId: "t", actor: "a", expectedTaskRevision: 1, leaseSeconds: 15, idempotencyKey: "c" }); transitionTask(d, { boardId: "b", taskId: "t", actor: "a", attemptId: c.attemptId, claimToken: c.claimToken!, expectedRevision: 2, target: "blocked", reason: "broken", idempotencyKey: "x" }); expect(d.prepare("SELECT state FROM fs_attempts").get()).toEqual({ state: "failed" }); expect(() => transitionTask(d, { boardId: "b", taskId: "t", actor: "a", attemptId: c.attemptId, claimToken: c.claimToken!, expectedRevision: 3, target: "done", idempotencyKey: "y" })).toThrow(TaskTransitionError); });
it("rejects a transition after the attempt expires", () => { const d = open(); const c = claimAttempt(d, { boardId: "b", taskId: "t", actor: "a", expectedTaskRevision: 1, leaseSeconds: 15, idempotencyKey: "c" }); const expiry = Math.floor(Date.now() / 1000) + 1; d.prepare("UPDATE fs_attempts SET expires_at = ? WHERE id = ?").run(expiry, c.attemptId); vi.setSystemTime((expiry + 1) * 1000); expect(() => transitionTask(d, { boardId: "b", taskId: "t", actor: "a", attemptId: c.attemptId, claimToken: c.claimToken!, expectedRevision: 2, target: "in_review", idempotencyKey: "expired" })).toThrow(TaskTransitionError); vi.useRealTimers(); });
it("treats the latest gate decision as authoritative", () => { const d = open(); const c = claimAttempt(d, { boardId: "b", taskId: "t", actor: "a", expectedTaskRevision: 1, leaseSeconds: 15, idempotencyKey: "c" }); const now = Date.now(); d.prepare("INSERT INTO fs_gates (board_id, id, name, required_for_json, created_at, updated_at) VALUES ('b', 'g', 'Gate', '[\"in_review\"]', ?, ?)").run(now, now); d.prepare("INSERT INTO fs_gate_decisions (board_id, task_id, gate_id, decision_no, status, actor, attempt_id, decided_at) VALUES ('b', 't', 'g', 1, 'allow', 'a', ?, ?), ('b', 't', 'g', 2, 'deny', 'a', ?, ?)").run(c.attemptId, now, c.attemptId, now); expect(() => transitionTask(d, { boardId: "b", taskId: "t", actor: "a", attemptId: c.attemptId, claimToken: c.claimToken!, expectedRevision: 2, target: "in_review", idempotencyKey: "denied-latest" })).toThrow(TaskTransitionError); });
