import { describe, expect, it } from "vitest";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import Database from "better-sqlite3";
import { createFreshStore } from "../../src/storage/bootstrap.js";
import { registerContractTools } from "../../src/tools/contracts.js";
import { registerPlanningTools } from "../../src/tools/planning.js";
import { createIdentityRuntime } from "../helpers/identity-runtime.js";

const make = (phase = "init", data: Record<string, unknown> = {}) => ({ board_id: "board", project: "p", change_name: "c", phase, status: "success", confidence: .9, executive_summary: "valid summary", data });
async function setup() { const db = new Database(":memory:"); createFreshStore(db); const server = new McpServer({ name: "t", version: "1" }); const identity = await createIdentityRuntime(server); registerPlanningTools(server, () => db); registerContractTools(server, () => db); const client = new Client({ name: "t", version: "1" }); const [a, b] = InMemoryTransport.createLinkedPair(); await Promise.all([server.connect(b), client.connect(a)]); const callTool = client.callTool.bind(client); (client as any).callTool = async (request: any, schema?: any) => { const args = request.arguments?._identity ? request.arguments : identity.signExactToolArgs(request.name, request.arguments ?? {}, { root: "test-root", parent: "test-parent", worker: (request.arguments as any)?.actor ?? "alice" }); const result: any = await callTool({ ...request, arguments: args }, schema); if (!result.structuredContent && result.content?.[0]?.text?.trimStart().startsWith("{")) result.structuredContent = JSON.parse(result.content[0].text); if (result.structuredContent?.ok !== undefined) result.structuredContent = result.structuredContent.ok ? result.structuredContent.data : { error: result.structuredContent.error }; return result; }; return { client, db }; }
async function board(client: Client) { return (await client.callTool({ name: "board_create", arguments: { actor: "alice", idempotency_key: "b", project: "p", name: "B" } })).structuredContent as any; }

describe("final contract tools", () => {
  it("registers exactly three contract names and validates without writing", async () => { const { client, db } = await setup(); expect((await client.listTools()).tools.map((x) => x.name).filter((x) => x.startsWith("contract_")).sort()).toEqual(["contract_commit", "contract_query", "contract_validate"]); const r = await client.callTool({ name: "contract_validate", arguments: { contract: make("plan") } }); expect(r.isError).toBe(true); db.close(); });
  it("bounds data and rejects unknown fields", async () => { const { client, db } = await setup(); const tooDeep: any = {}; let p = tooDeep; for (let i = 0; i < 10; i++) { p.x = {}; p = p.x; } const deep = await client.callTool({ name: "contract_validate", arguments: { contract: make("init", tooDeep) } }); expect(deep.isError).toBe(true); const unknown = await client.callTool({ name: "contract_validate", arguments: { contract: { ...make(), extra: true } } }); expect(unknown.isError).toBe(true); db.close(); });
  it("commits with digest, lineage, replay, CAS, and authority", async () => { const { client, db } = await setup(); const b = await board(client); const input = { actor: "alice", idempotency_key: "c1", expected_board_revision: b.revision, contract: { ...make(), board_id: b.id } }; const first = await client.callTool({ name: "contract_commit", arguments: input }); expect(first.isError).toBe(false); const value = first.structuredContent as any; expect(value.digest).toMatch(/^sha256:/); const replay = await client.callTool({ name: "contract_commit", arguments: input }); expect((replay.structuredContent as any).replayed).toBe(true); const conflict = await client.callTool({ name: "contract_commit", arguments: { ...input, contract: { ...input.contract, data: { changed: true } } } }); expect((conflict.structuredContent as any).error.code).toBe("IDEMPOTENCY_CONFLICT"); const denied = await client.callTool({ name: "contract_commit", arguments: { ...input, actor: "mallory", idempotency_key: "m1" } }); expect((denied.structuredContent as any).error.code).toBe("RESOURCE_NOT_AVAILABLE"); db.close(); });
  it("queries with actor authorization and bounds", async () => { const { client, db } = await setup(); const b = await board(client); const board_id = b.id; await client.callTool({ name: "contract_commit", arguments: { actor: "alice", idempotency_key: "c", expected_board_revision: b.revision, contract: { ...make(), board_id } } }); const q = await client.callTool({ name: "contract_query", arguments: { actor: "alice", board_id, limit: 1 } }); expect((q.structuredContent as any).items).toHaveLength(1); const bad = await client.callTool({ name: "contract_query", arguments: { actor: "alice", board_id, limit: 101 } }); expect(bad.isError).toBe(true); const denied = await client.callTool({ name: "contract_query", arguments: { actor: "mallory", board_id } }); expect((denied.structuredContent as any).error.code).toBe("RESOURCE_NOT_AVAILABLE"); db.close(); });
});
