export const IDENTITY_ERROR_CODES = ["IDENTITY_INVALID", "IDENTITY_ENCODING_INVALID", "IDENTITY_SIZE_EXCEEDED", "IDENTITY_SIGNATURE_INVALID", "IDENTITY_AUDIT_FAILED"] as const;
export type IdentityErrorCode = (typeof IDENTITY_ERROR_CODES)[number];
